// == sql.c ==
//
//   SQL does not allow forward references in FOREIGN KEY constraints on most
//   databases (MySQL, SQLite).  To avoid ordering problems entirely we split
//   the output into two passes:
//
//   Pass 1  CREATE TABLE statements without any FK constraints.
//             Every table is defined before any reference to it exists.
//
//   Pass 2  ALTER TABLE ... ADD CONSTRAINT FOREIGN KEY after all tables
//             are created.  This works universally across all SQL dialects.
//
// TYPE MAPPING:
//   The Property.type field stores short strings set by the tokeniser:
//     "int"    -> INT
//     "str"    -> VARCHAR(255)
//     "double" -> DOUBLE
//     "date"   -> DATE
//     "money"  -> DECIMAL(10,2)
//   Anything else falls back to VARCHAR(255) so unknown types don't break
//   the output file.
//
// FK CONSTRAINT NAMING:
//   Each FK constraint is named  fk_<table>_<column>  to avoid name
//   collisions when multiple FKs exist on the same table.
//
// JUNCTION TABLE PK+FK COLUMNS:
//   In N:N relationships the junction table's PK columns also act as FKs.
//   The Property struct stores both keytype==PRIMARY_KEY and references[]
//   on the SAME column, so Pass 2 emits ALTER TABLE for any property
//   with references[] set, not just FOREIGN_KEY properties.
//
// COMPOSITE PRIMARY KEYS:
//   Junction tables (N,N relationships) get multiple PK columns migrated
//   from both parent entities.  SQL only allows one PRIMARY KEY clause per
//   table, so when a table has >1 PK column we emit a separate
//     PRIMARY KEY (col1, col2, ...)
//   line instead of inline PRIMARY KEY on each column.
//
// PRECONDITION CHECK:
//   If global_objects.current_dtype != MLD we refuse to generate SQL and
//   show an error.  The user must convert to MLD first.

#include "sql.h"
#include "../MCD_elements.h"
#include "../command_processor.h"
#include "../global_objects.h"
#include <stdio.h>
#include <string.h>

// helpers
static const char *map_type(const char *mcd_type) {
    if (strcmp(mcd_type, "int") == 0)
        return "INT";
    if (strcmp(mcd_type, "str") == 0)
        return "VARCHAR(255)";
    if (strcmp(mcd_type, "double") == 0)
        return "DOUBLE";
    if (strcmp(mcd_type, "date") == 0)
        return "DATE";
    if (strcmp(mcd_type, "money") == 0)
        return "DECIMAL(10,2)";
    return "VARCHAR(255)"; // safe fallback for unknown types
}

bool generate_sql(const char *filename, WINDOW *console_win) {
    if (!filename || filename[0] == '\0') {
        show_message(console_win, "SQL export failed: no filename given");
        return false;
    }

    if (global_objects.current_dtype != MLD) {
        show_message(console_win, "Convert to MLD first before exporting SQL");
        return false;
    }

    FILE *f = fopen(filename, "w");
    if (!f) {
        show_message(console_win, "SQL export failed: could not open file for writing");
        return false;
    }

    fprintf(f, "-- Generated by MCD Tool\n");
    fprintf(f, "-- Pass 1: Table definitions\n\n");

    for (int i = 0; i < global_objects.entity_count; i++) {
        Entity *e = global_objects.entities[i];
        if (!e)
            continue;

        // Collect PK columns and regular columns separately
        Property *pks[16];
        Property *cols[64];
        int pk_count = 0, col_count = 0;

        for (int j = 0; j < e->num_properties; j++) {
            Property *p = e->properties[j];
            if (!p)
                continue;
            if (p->keytype == PRIMARY_KEY)
                pks[pk_count++] = p;
            else
                cols[col_count++] = p;
        }

        fprintf(f, "CREATE TABLE %s (\n", e->name);

        int line_count = 0;
        int total_lines = col_count + pk_count + (pk_count > 1 ? 1 : 0);

        // Regular columns first (FKs and NORMAL_KEYs)
        for (int j = 0; j < col_count; j++) {
            const char *comma = (++line_count < total_lines) ? "," : "";
            fprintf(f, "    %s %s%s\n", cols[j]->name, map_type(cols[j]->type), comma);
        }

        // PK columns
        for (int j = 0; j < pk_count; j++) {
            const char *comma = (++line_count < total_lines) ? "," : "";
            if (pk_count == 1) {
                // Single PK: inline constraint
                fprintf(f, "    %s %s PRIMARY KEY%s\n", pks[j]->name, map_type(pks[j]->type), comma);
            } else {
                // Multiple PKs: just the column, composite constraint comes after
                fprintf(f, "    %s %s%s\n", pks[j]->name, map_type(pks[j]->type), comma);
            }
        }

        // Composite PRIMARY KEY constraint
        if (pk_count > 1) {
            fprintf(f, "    PRIMARY KEY (");
            for (int j = 0; j < pk_count; j++) {
                fprintf(f, "%s%s", pks[j]->name, (j < pk_count - 1) ? ", " : "");
            }
            fprintf(f, ")\n");
        }

        fprintf(f, ");\n\n");
    }

    // Pass 2: Foreign key constraints
    // Emit ALTER TABLE for any property that has 'references' set,
    // including PRIMARY_KEY columns in junction tables (N:N) that
    // reference their parent entities.
    bool any_fk = false;
    for (int i = 0; i < global_objects.entity_count; i++) {
        Entity *e = global_objects.entities[i];
        if (!e)
            continue;

        for (int j = 0; j < e->num_properties; j++) {
            Property *p = e->properties[j];
            if (!p)
                continue;
            if (p->references[0] == '\0')
                continue; // no reference recorded, skip

            if (!any_fk) {
                fprintf(f, "-- Pass 2: Foreign key constraints\n\n");
                any_fk = true;
            }

            // Use references_column if set (original PK name in source entity),
            // otherwise fall back to p->name (for backward compatibility).
            const char *ref_col = (p->references_column[0] != '\0') ? p->references_column : p->name;

            fprintf(f, "ALTER TABLE %s\n", e->name);
            fprintf(f, "    ADD CONSTRAINT fk_%s_%s\n", e->name, p->name);
            fprintf(f, "    FOREIGN KEY (%s) REFERENCES %s(%s);\n\n", p->name, p->references, ref_col);
        }
    }

    fclose(f);

    char msg[128];
    snprintf(msg, sizeof(msg), "SQL exported to '%s'", filename);
    show_message(console_win, msg);
    return true;
}
